# 第5章 错误与异常

## 5.1 错误
 - 语法错误：Syntax Error
 - 当python检测到错误则无法执行，从而抛出提示信息，即为异常

## 5.2 异常

- 常见异常以及描述

|异常|描述|
|---|---|
|NameError   |尝试访问一个没有声明的变量（虽然不需要声明，但是变量必须先赋值才能使用）|
|ZeroDivisionError|除数为0|
|SyntaxError|语法错误|
|IndexError|索引超出序列范围；例如：a = [1, 2, 3]   a[4]|
|KeyError|请求一个不存在的字典关键字|
|IOError|输入/输出错误（例如文件不存在,或者文件路径不正确）|
|AttributeError|尝试访问未知的对象类型|   

## 5.3 处理异常


### 5.3.1 使用try....except...

```python
while 1:
    print("This is a program")
    c = input("input 'c' continue,otherwise logout:")
    if c == "c":
        a = input("first number:")
        b = input("second number:")
        try:
            print(float(a)/float(b))
            print("*************")
        except ZeroDivisionError: #当try中没有异常则此部分不执行，如果try子句中有异常，则执行except后面指定的异常类型及其子句
            # 如果except后面没有任何异常类型，则无论try发生什么异常均执行except
            print("the second number can not be zero")
            print("*************")
        except ValueError: # 可以通过怎么except，可以处理多个异常
            print("please input number.")
            print("*************")

        #以上两个except可以合成一个
        except (ZeroDivisionError, ValueError):
            print("please input rightly")
            print("**************")

        # 使用系统默认的异常提示，打印出来但是程序不中断
        except (ZeroDivisionError, ValueError) as e:
            print(e)
            print("**************")
        else:# 如果执行了try ，则except不执行，但是执行else
            print("hello")
        finally: # 不管前面执行try 还是except，都要执行finally
            del e
    else:
        break

```
此程序需在终端中执行


### 5.3.2 assert使用

```python
# assert 用于判定断言，等价于布尔运算
#默认值为真，当发生异常则值为假

class Accout(object):
    def __init__(self,number):
        self.number = number
        self.balance = 0

    def deposit(self, amount):
        try:
            assert amount > 0
            self.balance += amount
        except:
            print("The money should bigger than zero")

    def withdraw(self, amount):
        assert amount > 0
        if amount <= self.balance:
            self.balance -= amount
        else:
            print("balance is not enough")

if __name__ == "__main__":
    a = Accout(1000)
    a.deposit(-10)
```
程序运行结果：
`The money should bigger than zero`

- assert通常使用情况
  - 防御性的编程
  - 运行时对程序逻辑的检测
  - 合约性检查（例如前置条件、后置条件）
  - 程序中的常量
  - 检查文档